# Generated by Django 4.1.4 on 2022-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0003_remove_appuser_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting.'),
        ),
    ]
