# Generated by Django 4.1.4 on 2022-12-20 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0005_alter_appuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='recoveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_longitude', models.IntegerField(default=None)),
                ('location_latitude', models.IntegerField(default=None)),
                ('recovery_type', models.CharField(max_length=30)),
                ('vehicle_condition', models.CharField(max_length=30)),
                ('assigned_volunteers', models.CharField(default=None, max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
