# Generated by Django 4.1.4 on 2022-12-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0006_recoveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveries',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
