# Generated by Django 4.1.4 on 2022-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0008_alter_recoveries_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveries',
            name='assigned_volunteers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
