# Generated by Django 4.1.4 on 2022-12-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0009_alter_recoveries_assigned_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveries',
            name='after_action_report',
            field=models.TextField(default=None),
        ),
    ]
