# Generated by Django 4.1.4 on 2022-12-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0010_recoveries_after_action_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveries',
            name='after_action_report',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recoveries',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
