# Generated by Django 4.1.4 on 2022-12-23 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0011_alter_recoveries_after_action_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveries',
            name='recovery_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
