# Generated by Django 4.1.4 on 2022-12-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offroad_app', '0012_recoveries_recovery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveries',
            name='completed',
        ),
        migrations.AddField(
            model_name='recoveries',
            name='status',
            field=models.CharField(default='in-progress', max_length=12),
        ),
    ]
